name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
      
    - name: Build (with TypeScript check)
      run: npm run build
      env:
        # Placeholder values for CI only - real values should be in GitHub secrets
        NEXT_PUBLIC_SUPABASE_URL: "https://example.com"
        NEXT_PUBLIC_SUPABASE_ANON_KEY: "example-key"
    
    - name: Test
      run: npm test
      if: ${{ false }}  # Disabled until tests are added
